camera:
  coeffsPath: "../config/camera_coeffs.yml"
  width: 640
  height: 480
aiming:
  compensator:
    processCompensateTime: 0.0
    maxNumIterations: 100
  basic:
    detConfidenceThreshold: 0.55
    debugShowVisionInput: false
    debugShowTracker: true
    airResistanceConst: 0.1
tracker:
  minHitCount: 3
  maxMissingCount: 12
  similarityThreshold: 0.5
  maxScreenDist: 30
  bboxDilate: 3.5
kalman:
  processNoiseCov:
    SC: 0.05
  measurementNoiseCov:
    SCM: 0.1
  processInterval: 0.05
predictor:
  rune:
    avgUpdateTimeInterval: 0.02
    predAmpRange: 0.5
    predOmegaRange: 0.5
transformer:
  camToGimbalT:
    rot:
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
    trans:
      x: 0.0
      y: 0.0
      z: 0.0
globalRule:
  isStandard3Large: false
  isStandard4Large: false
  isStandard5Large: false
