camera:
  coeffsPath: "/home/catslashbin/Projects/Cygnoides-Decision/config/camera_coeffs.yml"
  width: 1080
  height: 1024
aiming:
  basic:
    compensateTime: 5.0
  airResistanceConst: 0.1
tracker:
  minHitCount: 2
  maxMissingCount: 5
  similarityThreshold: 0.65
kalman:
  processNoiseCov:
    SD: 1e-1
    SR: 1e-1
    SH: 1e-1
    SC: 1e-1
  measurementNoiseCov:
    SDM: 150
    SRM: 100
    SHM: 100
    SCM: 100
predictor:
  rune:
    avgUpdateTimeInterval: 0.02
    predAmpRange: 0.5
    predOmegaRange: 0.5
transformer:
  camToGimbalT:
    rot:
      yaw: 0.0
      pitch: 0.0
      roll: 0.0
    trans:
      x: 0.0
      y: 0.0
      z: 0.0